const house = [
    {
        header: "East Tamaki, 3 bedrooms",
        address: "5/325 Ti-Raku Drive, East Tamaki, Manukau City, Auckland",
        location: "Auckland",
        district: "Manukau City",
        suburb: "East Tamaki",
        type: "Apartment",
        bedroom: 3,
        bathroom: 1,
        parking: 1,
        pet: "pet friendly",
        cost: 700,
        furnish: "no",
        pictures: {
            1: "https://trademe.tmcdn.co.nz/photoserver/plus/1830345358.jpg",
            2: "https://trademe.tmcdn.co.nz/photoserver/plus/1830345284.jpg",
            3: "https://trademe.tmcdn.co.nz/photoserver/plus/1830345301.jpg",
            4: "https://trademe.tmcdn.co.nz/photoserver/plus/1830345312.jpg",
            5: "https://trademe.tmcdn.co.nz/photoserver/plus/1830345324.jpg",
            6: "https://trademe.tmcdn.co.nz/photoserver/plus/1830345336.jpg",
            7: "https://trademe.tmcdn.co.nz/photoserver/plus/1830345343.jpg",
        },
    },
    {
        header: "Massey, 4 bedrooms",
        address: "247 Don Buck Road, Massey, Waitakere City, Auckland",
        location: "Auckland",
        district: "Waitakere City",
        suburb: "Massey",
        type: "House",
        bedroom: 4,
        bathroom: 1.5,
        parking: 3,
        pet: "no pets",
        cost: 700,
        furnish: "part",
        pictures: {
            1: "https://trademe.tmcdn.co.nz/photoserver/plus/1830346658.jpg",
            2: "https://trademe.tmcdn.co.nz/photoserver/plus/1830346675.jpg",
            3: "https://trademe.tmcdn.co.nz/photoserver/plus/1830346696.jpg",
            4: "https://trademe.tmcdn.co.nz/photoserver/plus/1830346710.jpg",
            5: "https://trademe.tmcdn.co.nz/photoserver/plus/1830346727.jpg",
            6: "https://trademe.tmcdn.co.nz/photoserver/plus/1830346780.jpg",
            7: "https://trademe.tmcdn.co.nz/photoserver/plus/1830346741.jpg",
        },
    },
    {
        header: "Belmont, 2 bedrooms",
        address: "2/1A Fifeshire, Belmont, North Shore City, Auckland",
        location: "Auckland",
        district: "North Shore City",
        suburb: "Belmont",
        type: "Apartment",
        bedroom: 2,
        bathroom: 1,
        parking: 2,
        pet: "no pets",
        cost: 650,
        furnish: "yes",
        pictures: {
            1: "https://trademe.tmcdn.co.nz/photoserver/plus/1830908226.jpg",
            2: "https://trademe.tmcdn.co.nz/photoserver/plus/1830908172.jpg",
            3: "https://trademe.tmcdn.co.nz/photoserver/plus/1830908179.jpg",
            4: "https://trademe.tmcdn.co.nz/photoserver/plus/1830908187.jpg",
            5: "https://trademe.tmcdn.co.nz/photoserver/plus/1830908198.jpg",
            6: "https://trademe.tmcdn.co.nz/photoserver/plus/1830908220.jpg",
            7: "https://trademe.tmcdn.co.nz/photoserver/plus/1830908165.jpg",
        },
    },
    {
        header: "Island Bay, 4 bedrooms",
        address: "23 Dargle Way, Island Bay, Wellington, Wellington",
        location: "Wellington",
        district: "Wellington",
        suburb: "Island Bay",
        type: "House",
        bedroom: 4,
        bathroom: 2,
        parking: 3,
        pet: "no pets",
        cost: 1050,
        furnish: "no",
        pictures: {
            1: "https://trademe.tmcdn.co.nz/photoserver/plus/1830693528.jpg",
            2: "https://trademe.tmcdn.co.nz/photoserver/plus/1830693520.jpg",
            3: "https://trademe.tmcdn.co.nz/photoserver/plus/1830694145.jpg",
            4: "https://trademe.tmcdn.co.nz/photoserver/plus/1830694152.jpg",
            5: "https://trademe.tmcdn.co.nz/photoserver/plus/1830694165.jpg",
            6: "https://trademe.tmcdn.co.nz/photoserver/plus/1830694176.jpg",
            7: "https://trademe.tmcdn.co.nz/photoserver/plus/1830694188.jpg",
            8: "https://trademe.tmcdn.co.nz/photoserver/plus/1830694195.jpg",
            9: "https://trademe.tmcdn.co.nz/photoserver/plus/1830694215.jpg",
            10: "https://trademe.tmcdn.co.nz/photoserver/plus/1830694244.jpg",
        },
    },
    {
        header: "Bluff Hill, 2 bedrooms",
        address: "5A Seapoint Road, Bluff Hill, Napier, Hawke's Bay",
        location: "Hawke's Bay",
        district: "Napier",
        suburb: "Bluff Hill",
        type: "House",
        bedroom: 2,
        bathroom: 2,
        parking: 3,
        pet: "pet friendly",
        cost: 590,
        furnish: "no",
        pictures: {
            1: "https://trademe.tmcdn.co.nz/photoserver/plus/1830689983.jpg",
            2: "https://trademe.tmcdn.co.nz/photoserver/plus/1830689990.jpg",
            3: "https://trademe.tmcdn.co.nz/photoserver/plus/1830689994.jpg",
            4: "https://trademe.tmcdn.co.nz/photoserver/plus/1830689996.jpg",
            5: "https://trademe.tmcdn.co.nz/photoserver/plus/1830690000.jpg",
            6: "https://trademe.tmcdn.co.nz/photoserver/plus/1830690002.jpg",
            7: "https://trademe.tmcdn.co.nz/photoserver/plus/1830690007.jpg",
            8: "https://trademe.tmcdn.co.nz/photoserver/plus/1830690015.jpg",
            9: "https://trademe.tmcdn.co.nz/photoserver/plus/1830690034.jpg",
            10: "https://trademe.tmcdn.co.nz/photoserver/plus/1830690039.jpg",
            11: "https://trademe.tmcdn.co.nz/photoserver/plus/1830690054.jpg",
            12: "https://trademe.tmcdn.co.nz/photoserver/plus/1830690059.jpg",
        },
    },
]

export default house
